import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <article>
        <h1>Lorem ipsum dolor sit amet.</h1>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia,
          provident natus. Modi placeat earum, officiis harum quidem ipsam quasi
          sapiente beatae eum sunt ab ea vero explicabo deserunt dignissimos
          minima.
        </p>
      </article>
    </div>
  );
};

export default Home;
